### ISSUE TITLE
Cambiar iconos

### ISSUE THREAD

**Issue by Feer93** [UNIZAR-30226-2021-10/front-end-web#33]
Hay que cambiar los iconos de las páginas Historial, Decisión Juego. Utilizar fa-fa icons de la libreria : '@fortawesome/free-solid-svg-icons'

**Comment by Feer93** [comment]
También hay que cambiar los iconos en la pantalla ranking.

**Comment by Lulay7** [comment]
He cambiado mas o menos todos los iconos menos los de las medallitas de ranking porque se me han hecho bola.
La gracia es que hay un icono de medalla y si le metes un < span style= { { color: "color-ejemplo" } } > le puedes cambiar el color para que sea oro, plata y bronce.
De todas formas se pueden quitar y fin, pero si quieres @Feer93 ahí está la idea
