### ISSUE TITLE
Modificar avatar bien

### ISSUE THREAD

**Issue by Lulay7** [UNIZAR-30226-2021-10/front-end-web#34]
Meterle diseño a lo de modificar avatar para que se vea bonito, en plan que cuando haces click en un item se mantenga seleccionado, etc.

**Comment by Feer93** [comment]
He añadido una cajita alrededor cuando lo lleva equipado, se podría añadir algun fa-faicon o incluso un header debajo indicando **EQUIPADO**

De todas formas el grueso para hacerlo está hecho así que cierro issue. @Lulay7 @newfeels
